### ISSUE TITLE
Pattern for approaching SoftDeletes

### ISSUE THREAD

**Issue by ggreenleaftc** [urfnet/URF.NET#35]
Would like to get some advice on how to approach Soft Deletes for our tables. If we assume that all tables in our Database have a IsDeleted bit. What would be the best approach for the following

- Marking Related Entities for Delete
    - How do we grab the related entities in code similar to the entity Includes?
    - Currently having to do several Includes and Selects to traverse the tree is ugly and trying to avoid using linq query syntax over several joins as well. 

- Filter related Entities after delete once they are deleted
    - Is there a default filter we can apply when using a queryable() so all nested items are automatically filtered based on a specified column?

**Comment by tonysneed** [comment]
@lelong37 Do you want to answer this one?

**Comment by lelong37** [comment]
yes, you should be able to inherit any `IRepository<TEntity>` e.g. `class ProductRepository: IRepository<TEntity>`, so for example, if you wanted to apply a default filter for all things ProductRepository simply override the any of your methods and apply your default filter, this way moving forward, all queries for Products we'll have your predefined filter already applied. Same pattern for soft deletes, inherit and override Delete and instead of doing a delete just do an Update in the override to mark items Deleted vs. actually do a hard delete.
